services:
  api:
    build: ./API
    networks:
      - mynetwork
    ports:
      - "5214:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=ASMDB;Port=5432;Database=asmDataBase;Username=postgres;Password=zaq1@WSX

    depends_on:
      - ASMDB

  ASMDB:
    image: postgres:latest
    container_name: asmdb
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: asmDataBase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zaq1@WSX
    volumes:
      - asmdb_data:/var/lib/postgresql/data

volumes:
  asmdb_data:

networks:
  mynetwork:
    driver: bridge